language: go
go:
  - 1.11
  - 1.12
env:
  - CGO_ENABLED=0
  - GOPATH=..
install: true
script:
        #- go vet $(go list ./... | grep -v vendor)
  - cd eventsservice && go build
    #  - cd bookingservice && go build
